language: php
#sudo: false

php:
    - 7.1
    - 7.2
    - 7.3
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

services:
    - mysql
    - mongodb
    - redis-server
    - memcached

notifications:
    email:
        - daniel.gonzalez@freelancemadrid.es

before_script:
    # Create Mysql Database
    - mysql -e 'CREATE DATABASE IF NOT EXISTS `cache`;'
    - mysql -e 'USE `cache`; CREATE TABLE `cache` (`k` varchar(255) NOT NULL, `v` text NOT NULL, `t` int(11) NOT NULL, PRIMARY KEY (`k`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;'

    # Enable extensions
    - sh -c "yes '' | pecl install mongodb"
    - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then phpenv config-add ./tests/travis/php.ini; fi"

    # Install dependencies
    - composer self-update
    - composer require --dev "satooshi/php-coveralls:~0.6"
    - mkdir -p build/logs

    # Set Configuration
    - cp tests/config.json.dist tests/config.json
    - cp tests/travis/phpunit.xml phpunit.xml

script:
    - phpunit -c ./phpunit.xml -v

after_script:
    - ls
    - php vendor/bin/coveralls -v
