language: php
#sudo: false

php:
    - 7.1
    - 7.2
    - nightly

matrix:
    allow_failures:
        - php: nightly

services:
    - mysql
    - mongodb
    - redis-server
    - memcached

notifications:
    email:
        - daniel.gonzalez@freelancemadrid.es

before_script:
    # Create Mysql Database
    - mysql -e 'CREATE DATABASE IF NOT EXISTS `cache`;'
    - mysql -e 'USE `cache`; CREATE TABLE `cache` (`k` varchar(255) NOT NULL, `v` text NOT NULL, `t` int(11) NOT NULL, PRIMARY KEY (`k`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;'

    # Enable extensions
    - yes '' | pecl install --soft mongodb
    - >
        test "$TRAVIS_PHP_VERSION" != "nightly" ||
        sh -c "
          cd /tmp &&
          pecl download memcached-3.0.4 &&
          tar zxvf memcached-3.0.4.tgz &&
          cd memcached-3.0.4 &&
          phpize &&
          ./configure --with-php-config=/home/travis/.phpenv/versions/master/bin/php-config --with-libmemcached-dir=no --disable-memcached-sasl &&
          make &&
          make install
        "
    - ls .travis/*.ini | xargs phpenv config-add

    # Install dependencies
    - composer self-update
    - composer require --dev "satooshi/php-coveralls:~0.6"
    - mkdir -p build/logs

script:
    - phpunit -v --coverage-text --coverage-xml=./build/logs/clover.xml

after_script:
    - ls
    - php vendor/bin/coveralls -v

